import xml.etree.ElementTree as ET

input = ''' 
<commentinfo>
<note>
This file contains the actual data for your assignment - good luck!
</note>
<comments>
<comment>
<name>Giane</name>
<count>96</count>
</comment>
<comment>
<name>Malaika</name>
<count>94</count>
</comment>
<comment>
<name>Creag</name>
<count>93</count>
</comment>
<comment>
<name>Brad</name>
<count>93</count>
</comment>
<comment>
<name>Lauchlin</name>
<count>93</count>
</comment>
<comment>
<name>Zara</name>
<count>90</count>
</comment>
<comment>
<name>Aishah</name>
<count>89</count>
</comment>
<comment>
<name>Samanthalee</name>
<count>89</count>
</comment>
<comment>
<name>Al</name>
<count>78</count>
</comment>
<comment>
<name>Tiernan</name>
<count>77</count>
</comment>
<comment>
<name>Jaxson</name>
<count>76</count>
</comment>
<comment>
<name>Elize</name>
<count>74</count>
</comment>
<comment>
<name>Taylor</name>
<count>73</count>
</comment>
<comment>
<name>Suilven</name>
<count>72</count>
</comment>
<comment>
<name>Juwairiyah</name>
<count>69</count>
</comment>
<comment>
<name>Tayyab</name>
<count>68</count>
</comment>
<comment>
<name>Kyan</name>
<count>64</count>
</comment>
<comment>
<name>Annalisa</name>
<count>62</count>
</comment>
<comment>
<name>Lekiesha</name>
<count>61</count>
</comment>
<comment>
<name>Kerris</name>
<count>60</count>
</comment>
<comment>
<name>Reeha</name>
<count>60</count>
</comment>
<comment>
<name>Iona</name>
<count>57</count>
</comment>
<comment>
<name>Rafael</name>
<count>57</count>
</comment>
<comment>
<name>Sorrel</name>
<count>56</count>
</comment>
<comment>
<name>Anubhav</name>
<count>51</count>
</comment>
<comment>
<name>Connell</name>
<count>48</count>
</comment>
<comment>
<name>Husnain</name>
<count>47</count>
</comment>
<comment>
<name>Vincent</name>
<count>46</count>
</comment>
<comment>
<name>Serena</name>
<count>43</count>
</comment>
<comment>
<name>Tessa</name>
<count>40</count>
</comment>
<comment>
<name>Samya</name>
<count>34</count>
</comment>
<comment>
<name>Arandeep</name>
<count>34</count>
</comment>
<comment>
<name>Guillaume</name>
<count>33</count>
</comment>
<comment>
<name>Karali</name>
<count>30</count>
</comment>
<comment>
<name>Axel</name>
<count>29</count>
</comment>
<comment>
<name>Sorley</name>
<count>27</count>
</comment>
<comment>
<name>Marios</name>
<count>27</count>
</comment>
<comment>
<name>Kaylah</name>
<count>26</count>
</comment>
<comment>
<name>Marie</name>
<count>24</count>
</comment>
<comment>
<name>Ander</name>
<count>22</count>
</comment>
<comment>
<name>Yoji</name>
<count>17</count>
</comment>
<comment>
<name>Dylin</name>
<count>16</count>
</comment>
<comment>
<name>Cali</name>
<count>16</count>
</comment>
<comment>
<name>Oliwia</name>
<count>12</count>
</comment>
<comment>
<name>Jad</name>
<count>11</count>
</comment>
<comment>
<name>Roman</name>
<count>8</count>
</comment>
<comment>
<name>Alf</name>
<count>5</count>
</comment>
<comment>
<name>Eddie</name>
<count>5</count>
</comment>
<comment>
<name>Koddi</name>
<count>3</count>
</comment>
<comment>
<name>Harriet</name>
<count>3</count>
</comment>
</comments>
</commentinfo>'''

commentinfo = ET.fromstring(input)
lst = commentinfo.findall('comments/comment')

numlist = list()

for item in lst:
    numlist.append(float(item.find('count').text))
    
# print numlist
print sum(numlist)
    

